name = "mysite-btns"
compatibility_date = "2024-12-01"

[build]
command = "npm run build"
cwd = "./"

[env.production]
vars = { ENVIRONMENT = "production" }

[assets]
directory = "./dist"
binding = "ASSETS"
