name = "mysite-btns"
type = "javascript"
compatibility_date = "2024-12-01"
compatibility_flags = ["streams_enable_constructors"]

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.{js,jsx,css}"]

[build.upload]
format = "service-worker"
